# Generated by Django 4.2.29 on 2026-03-09 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('first_qr_data', models.TextField()),
                ('first_qr_id', models.CharField(max_length=255)),
                ('second_qr_data', models.TextField(blank=True, null=True)),
                ('second_qr_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_match', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
