# Generated by Django 4.2.29 on 2026-03-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('first_qr_data', models.TextField()),
                ('first_qr_id', models.CharField(max_length=255)),
                ('second_qr_data', models.TextField(blank=True, null=True)),
                ('second_qr_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_match', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
