# Generated by Django 4.2.29 on 2026-03-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.TextField(help_text='Data encoded in the QR code')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('coil', 'Coil'), ('object', 'Object'), ('produced_item', 'Produced Item'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('qr_image_base64', models.TextField(help_text='Base64-encoded PNG image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
