# Generated by Django 4.2.29 on 2026-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='match_key',
            field=models.CharField(default='', help_text='The string to search for when matching with another QR code', max_length=255),
        ),
        migrations.AddField(
            model_name='scansession',
            name='match_key',
            field=models.CharField(blank=True, default='', help_text='The key used to search in QR #2', max_length=255),
        ),
        migrations.AddField(
            model_name='scansession',
            name='match_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
