# Generated by Django 4.2.29 on 2026-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_qrcode_match_key_scansession_match_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='match_key',
            field=models.TextField(default='', help_text='Comma-separated keywords to search for when matching with another QR code'),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='match_key',
            field=models.TextField(blank=True, default='', help_text='The key(s) used to search in QR #2'),
        ),
    ]
