services:
  - type: web
    name: qr-scanner-api
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        sync: false
